// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Countdown: typeof import('./src/components/countdown/index.vue')['default']
    LottieView: typeof import('./src/components/lottieView/index.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCheckboxGroup: typeof import('@nutui/nutui-taro')['CheckboxGroup']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutCountdown: typeof import('@nutui/nutui-taro')['Countdown']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPicker: typeof import('@nutui/nutui-taro')['Picker']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutProgress: typeof import('@nutui/nutui-taro')['Progress']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutStep: typeof import('@nutui/nutui-taro')['Step']
    NutSteps: typeof import('@nutui/nutui-taro')['Steps']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    Uploader: typeof import('./src/components/uploader/index.vue')['default']
  }
}
